# Generated by Django 5.2.10 on 2026-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_is_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('deadline_warning', 'Deadline Warning'), ('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned')], default='status_change', max_length=20),
        ),
    ]
