# Generated by Django 5.2.10 on 2026-01-09 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline', 'priority_escalated', 'status'], name='tasks_task_deadlin_ab25e9_idx'),
        ),
    ]
